# install needed packages
parameters:
- name: pythonVersion
  type: string
- name: condaEnv
  type: string
  default: interpret_conda_env

steps:
  - bash: brew install libomp
    displayName: Use Homebrew to install libomp on MacOS
    condition:  eq(variables['Agent.OS'], 'Darwin')

  - bash: conda create --yes --quiet --name ${{parameters.condaEnv}} python=${{parameters.pythonVersion}}
    displayName: Create Anaconda environment

  - bash: |
      source activate ${{parameters.condaEnv}}
      conda install --yes --quiet --name  ${{parameters.condaEnv}} pytorch-cpu torchvision-cpu -c pytorch
      conda install --yes -c anaconda -n  ${{parameters.condaEnv}} jupyter pip
    displayName: Install Anaconda packages

  - bash: |
      source activate  ${{parameters.condaEnv}}
      conda install --yes -c conda-forge lightgbm
    displayName: Install lightgbm from conda on MacOS
    condition:  eq(variables['Agent.OS'], 'Darwin')

  - bash: |
      source activate ${{parameters.condaEnv}} 
      pip install --upgrade pip
    displayName: Upgrade pip to latest

  - bash: |
      source activate  ${{parameters.condaEnv}} 
      pip install -r requirements.txt
    displayName: Install required pip packages

  - bash: |
      source activate  ${{parameters.condaEnv}} 
      conda install --yes -c conda-forge -n interp papermill 
      pip install nteract-scrapbook
    displayName: List Jupyter Kernel and fix
